# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /

# Setup
title:               Hong's
tagline:             'blog'
description:         'Posting about<br>Artificial Intelligence<br>Android<br>Computer Science, etc'
url:                 http://lanyon.getpoole.com
baseurl:             ""
paginate:            5
encoding: utf-8
  

# About/contact
author:
  name: Hong seong hak
  email: hongdroid.ai@gmail.com

# Custom vars
version:             1.0.0
