# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /

# Setup
title:               Hong's
tagline:             'blog'
description:         'Posting about Artificial Intelligence / Android / Computer Science, etc'
url:                 http://lanyon.getpoole.com
baseurl:             ""
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
