# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /

# Setup
title:               Hong's
tagline:             'blog'
description:         '<p>Posting about</p> <p>Artificial Intelligence</p> <p>Android</p> <p>Computer Science, etc</p>'
url:                 http://lanyon.getpoole.com
baseurl:             ""
paginate:            5

# About/contact
author:
  name:              Hong seong hak
  url:               -
  email:             hongdroid.ai@gmail.com

# Custom vars
version:             1.0.0
